#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# cmk_modbus - Check_MK plugin to poll data from modbus-enabled devices
#
# Authors:
#   Mathias Krüger <noreply@ibh.de>
#
# Copyright Holder:
#   2016 (C) IBH IT-Service GmbH [http://www.ibh.de/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# e.g. agent_modbus --addr 192.168.0.1 502 UMG_96_RM-EL-230_50

modbus_templates_dir = os.path.expanduser('~') + "/etc/cmk_modbus/dev.d"

def agent_modbus_arguments(params, hostname, ipaddress):
    address = quote_shell_string(ipaddress)
    templates = quote_shell_string(modbus_templates_dir)
    device = quote_shell_string(params['dev'])

    args = "--addr {0} --port {1} --templates {2} --dev {3}".format(address, params['port'], templates, device)
    return args

special_agent_info['modbus'] = agent_modbus_arguments
